### ISSUE TITLE
Main differences from dockprom and migrating instructions

### ISSUE THREAD

**Issue by psychowood** [paaacman/promstack#1]
Hi,
I reached this project following your [comment](https://github.com/google/cadvisor/issues/2523#issuecomment-785094428) in a cadvisor issue.

This fork looks promising from what I reconstructed analyzing the changesets, though I'm not 100% sure I understood correctly the main differences with dockprom :)

Would you mind sharing your thoughts?

Can it replace 1:1 dockprom for common containers (e.g. can the data folder/volumes can be moved over directly)?

Thanks!

**Comment by paaacman** [comment]
Hello,
First, I apparently don't get notifications for issues, sorry for not replying earlier.

I don't think promstack is compatible with dockprom.
I changed a lot of things to adapt to my needs.
- Prometheus and Grafana volumes has the same name, networks are different.
- Configurations are not in the same files.

Here are some differences (see diff and commits) : 
- Add Loki and Promtail for logs.
- Add blackbox (ping urls).
- Remove pushgateway.
- Remove caddy - hosts use nginx, and promstack expose services locally.
- Configure things differently.
- Adapt cadvisor configuration.
- Add some Grafana dashboards.
